# Base simulation parameters
simulation_params:
  initial_balance: 100  # Initial balance for new accounts
  welcome_bonus: 200    # Welcome bonus for registration
  min_gas_price: 0
  max_gas_price: 50000000000
  mint_policy_address: "0x79Cbc9C7077dF161b92a745345A6Ade3fC626A60"

# Agent distribution (total should be your target network size)
agent_distribution:
  circles_user: 1
  circles_user2: 1

# Agent profiles and their actions
profiles:
  circles_user2:
    description: "Regular network participant"
    base_config:
      target_account_count: 1
      risk_tolerance: 0.5 
      sequence_probability: 1
      max_sequence_iterations: 10
      preset_addresses: 
        - "0x42cEDde51198D1773590311E2A340DC06B24cB37"

    action_sequences:
      - name: "full_setup_lbp"
        max_executions: 1
        steps:
          - action: "circleserc20lift_ensureERC20"
            repeat: 1
            constraints:
              _circlesType: 0

          - action: "custom_setupLBP"
            repeat: 1
            constraints:
              XDAI_AMOUNT: 100
              CRC_AMOUNT: 10
              WRAP_TYPE: 0
              BACKING_ASSET: '0xaf204776c7245bF4147c2612BF6e5972Ee483701'
              WEIGHT_CRC: 10000000000000000
              WEIGHT_BACKING: 990000000000000000

          - action: "custom_joinLBP"
            repeat: 1
            constraints:
              CRC_TYPE: 0
              
      - name: "lbp_arbitrage"
        max_executions: 1
        steps:
          - action: "custom_arbGetBackingToken"
            repeat: 1
            constraints: {}
          - action: "custom_arbBuyCRC"
            repeat: 1
            constraints: {}
          - action: "custom_arbUnWrapCRC"
            repeat: 1
            constraints: {}
          - action: "custom_arbPathFinder"  
            repeat: 1
            constraints: {}
          - action: "custom_arbWrapCRC"
            repeat: 1
            constraints: {}
          - action: "custom_arbSellToLBP"
            repeat: 1
            constraints: {}

    available_actions:
      - action: "custom_arbCheckOpportunity"
        probability: 0.5
        cooldown_blocks: 500

  circles_user:
    description: "Regular network participant"
    base_config:
      target_account_count: 1
      risk_tolerance: 0.5 
      sequence_probability: 0.3
      max_sequence_iterations: 1
      preset_addresses: 
        - "0xA6247834B41771022498F63CAE8820fFEE208265"
        - "0x14c16ce62d26Fd51582A646e2e30a3267b1E6D7E"

    action_sequences:
      - name: "full_setup_lbp"
        max_executions: 1
        steps:
          - action: "circleserc20lift_ensureERC20"
            repeat: 1
            constraints:
              _circlesType: 0

          - action: "custom_setupLBP"
            repeat: 1
            constraints:
              XDAI_AMOUNT: 100
              CRC_AMOUNT: 48
              WRAP_TYPE: 0
              BACKING_ASSET: '0xaf204776c7245bF4147c2612BF6e5972Ee483701'
              WEIGHT_CRC: 10000000000000000
              WEIGHT_BACKING: 990000000000000000

          - action: "custom_joinLBP"
            repeat: 1
            constraints:
              CRC_TYPE: 0

    #available_actions:   

    #  - action: "custom_pathFinderArb"
    #    probability: 0.1
    #    cooldown_blocks: 2

    #  - action: "circleshub_trust"
    #    probability: .6
    #    cooldown_blocks: 2

    #  - action: "circleshub_registerHuman"
    #    probability: 0.5
    #    cooldown_blocks: 2
        
    #  - action: "custom_setupLBP"
    #    probability: 1
    #    cooldown_blocks: 2
    #    constraints: {}

    #  - action: "circleshub_personalMint"
    #    probability: .6
    #    cooldown_blocks: 720

    #  - action: "circleshub_operateFlowMatrix"
    #    probability: 1.0
    #    cooldown_blocks: 10
    #    constraints:
    #      max_flow: 1000 #CRC
    #      min_flow: 1 #CRC

      