# Base simulation parameters
simulation_params:
  initial_balance: 100  # Initial balance for new accounts
  welcome_bonus: 200    # Welcome bonus for registration
  min_gas_price: 0
  max_gas_price: 50000000000
  mint_policy_address: "0x79Cbc9C7077dF161b92a745345A6Ade3fC626A60"

# Agent distribution (total should be your target network size)
agent_distribution:
  circles_user: 1
  circles_newuser: 0

# Agent profiles and their actions
profiles:
  circles_user:
    description: "Regular network participant"
    base_config:
      target_account_count: 1
      risk_tolerance: 0.5
      sequence_probability: 1
      max_sequence_iterations: 1
      preset_addresses: 
        - "0x42cEDde51198D1773590311E2A340DC06B24cB37"
        - "0xA6247834B41771022498F63CAE8820fFEE208265"
        - "0x14c16ce62d26Fd51582A646e2e30a3267b1E6D7E"

    action_sequences:
      - name: "full_setup_lbp"
        max_executions: 1
        steps:
          - action: "circleserc20lift_EnsureERC20"
            repeat: 1
            constraints:
              CRC_TYPE: 0

          - action: "batchcall_BatchCall"
            repeat: 1
            batchcall:
              setup_lbp: 1
            constraints:
              xDAI_value: 100
              CRC_value: 2
              CRC_TYPE: 0
              #CRC_token: '0xf48554937f18885c7f15c432c596b5843648231D' 
              BACKING_ASSET: '0xaf204776c7245bF4147c2612BF6e5972Ee483701'

          - action: "balancerv2vault_JoinPool"
            repeat: 1
            constraints:
              CRC_TYPE: 0
     

    available_actions:   
      - action: "circleshub_Trust"
        probability: 0.5
        cooldown_blocks: 2
        max_executions: 5


  circles_newuser:
    description: "Regular network participant with standard behavior"
    base_config:
      target_account_count: 100  # Number of accounts this agent controls
      max_daily_actions: 20    # Maximum actions per day
      preferred_networks: ["gnosis"]  # Preferred networks
      
    available_actions:
      - action: "circleshub_Wrap"
        probability: 0.5
        cooldown_blocks: 1
        max_value: 10.0
        constraints:
          min_balance: 1.0

      - action: "circleshub_Trust"
        probability: 1
        cooldown_blocks: 1

      - action: "circleshub_RegisterGroup"
        probability: 0.1
        cooldown_blocks: 10
        constraints:
          max_executions: 1

      - action: "circleshub_RegisterHuman"
        probability: .5
        cooldown_blocks: 1
        constraints:
          max_accounts_per_day: 5

      - action: "circleshub_PersonalMint"
        probability: 0.8
        cooldown_blocks: 2
        constraints:
          max_executions: 100

      - action: "circleshub_GroupMint"
        probability: 0.4
        cooldown_blocks: 1
        max_value: 50.0
 #       constraints:
 #         min_collateral_ratio: 1.5
 #         max_mint_per_day: 1000.0

      