# Base simulation parameters
simulation_params:
  initial_balance: 100  # Initial balance for new accounts
  welcome_bonus: 200    # Welcome bonus for registration
  min_gas_price: 0
  max_gas_price: 50000000000
  mint_policy_address: "0x79Cbc9C7077dF161b92a745345A6Ade3fC626A60"

# Agent distribution (total should be your target network size)
agent_distribution:
  arbitrage_user: 1
  circles_user: 1
  circles_user_old: 1

# Agent profiles and their actions
profiles:
  arbitrage_user:
    description: "Regular network participant"
    base_config:
      target_account_count: 1
      risk_tolerance: 0.5 
      sequence_probability: 0.6
      max_sequence_iterations: 10
      preset_addresses: 
        - "0x42cEDde51198D1773590311E2A340DC06B24cB37"
        - "0x57928Fb15ffB7303b65EDC326dc4dc38150008e1"

    action_sequences:
      - name: "full_setup_lbp"
        max_executions: 1
        steps:
          - action: "circleserc20lift_ensureERC20"
            repeat: 1
            constraints:
              _circlesType: 0

          - action: "custom_setupLBP"
            repeat: 1
            constraints:
              XDAI_AMOUNT: 100
              CRC_AMOUNT: 100
              WRAP_TYPE: 0
              BACKING_ASSET: '0xaf204776c7245bF4147c2612BF6e5972Ee483701'
              WEIGHT_CRC: 500000000000000000
              WEIGHT_BACKING: 500000000000000000

          - action: "custom_joinLBP"
            repeat: 1
            constraints:
              CRC_TYPE: 0
              
      - name: "lbp_arbitrage"
        max_executions: 1000
        steps:
          - action: "custom_arbCheckOpportunity"
            repeat: 1
            constraints: {}
          - action: "custom_arbGetBackingToken"
            repeat: 1
            constraints: {}
          - action: "custom_arbBuyCRC"
            repeat: 1
            constraints: {}
          - action: "custom_arbUnWrapCRC"
            repeat: 1
            constraints: {}
          - action: "custom_arbPathFinder"  
            repeat: 1
            constraints: {}
          - action: "custom_arbWrapCRC"
            repeat: 1
            constraints: {}
          - action: "custom_arbSellToLBP"
            repeat: 1
            constraints: {}

    available_actions:
      - action: "circleshub_trust"
        probability: .6
        cooldown_blocks: 100

      - action: "circleshub_registerHuman"
        probability: 0.5
        cooldown_blocks: 500

      - action: "circleshub_personalMint"
        probability: 0.6
        cooldown_blocks: 720


  circles_user:
    description: "Regular network participant"
    base_config:
      target_account_count: 100
      risk_tolerance: 0.5 
      sequence_probability: 0.6
      max_sequence_iterations: 1

    action_sequences:
      - name: "full_setup_lbp"
        max_executions: 1
        steps:
          - action: "circleserc20lift_ensureERC20"
            repeat: 1
            constraints:
              _circlesType: 0

          - action: "custom_setupLBP"
            repeat: 1
            constraints:
              XDAI_AMOUNT_MAX: 1000
              XDAI_AMOUNT_MIN: 10
              CRC_AMOUNT_MAX: 100
              CRC_AMOUNT_MIN: 1
              WRAP_TYPE: 0
              BACKING_ASSET: '0xaf204776c7245bF4147c2612BF6e5972Ee483701'
              WEIGHT_CRC_MIN: 10000000000000000
              WEIGHT_CRC_MAX: 990000000000000000

          - action: "custom_joinLBP"
            repeat: 1
            constraints:
              CRC_TYPE: 0

    available_actions:   

      - action: "circleshub_trust"
        probability: .6
        cooldown_blocks: 2

      - action: "circleshub_registerHuman"
        probability: 0.5
        cooldown_blocks: 2

      - action: "circleshub_personalMint"
        probability: .6
        cooldown_blocks: 720

  circles_user_old:
    description: "Regular network participant"
    base_config:
      target_account_count: 100
      risk_tolerance: 0.5 
      sequence_probability: 0.6
      max_sequence_iterations: 1
      preset_addresses: 
        - "0xA6247834B41771022498F63CAE8820fFEE208265"
        - "0x14c16ce62d26Fd51582A646e2e30a3267b1E6D7E"
        - "0xDE374ece6fA50e781E81Aac78e811b33D16912c7"
        - "0xD14ce9CFC6384590C6b77436dCA212a6Bcb2575F"

    action_sequences:
      - name: "full_setup_lbp"
        max_executions: 1
        steps:
          - action: "circleserc20lift_ensureERC20"
            repeat: 1
            constraints:
              _circlesType: 0

          - action: "custom_setupLBP"
            repeat: 1
            constraints:
              XDAI_AMOUNT_MAX: 100
              XDAI_AMOUNT_MIN: 10
              CRC_AMOUNT_MAX: 100
              CRC_AMOUNT_MIN: 10
              WRAP_TYPE: 0
              BACKING_ASSET: '0xaf204776c7245bF4147c2612BF6e5972Ee483701'
              WEIGHT_CRC_MIN: 200000000000000000
              WEIGHT_CRC_MAX: 800000000000000000

          - action: "custom_joinLBP"
            repeat: 1
            constraints:
              CRC_TYPE: 0

    available_actions:   

    #  - action: "custom_pathFinderArb"
    #    probability: 0.1
    #    cooldown_blocks: 2

      - action: "circleshub_trust"
        probability: .6
        cooldown_blocks: 2

      - action: "circleshub_registerHuman"
        probability: 0.5
        cooldown_blocks: 2
        

      - action: "circleshub_personalMint"
        probability: .6
        cooldown_blocks: 720

    #  - action: "circleshub_operateFlowMatrix"
    #    probability: 1.0
    #    cooldown_blocks: 10
    #    constraints:
    #      max_flow: 1000 #CRC
    #      min_flow: 1 #CRC

      